id: A42F87008
title: Light from the Wisdom Sun
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:39:02.329460
  last_modified_at: 2022-02-28 22:39:02.329464
