id: A42F87008
title: Long Life Prayer for Patrick Gaffney (Yeshé Wangyal)
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - nl
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:39:02.334149
  last_modified_at: 2022-02-28 22:39:02.334160
