id: A42F87008
title: Prayer for the Long Life of Alak Zenkar Rinpoche, the Incarnation of Do Khyentsé
  Yeshé Dorjé
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:39:02.343800
  last_modified_at: 2022-02-28 22:39:02.343803
