id: A42F87008
title: A Prayer for the Swift Rebirth of Tenpai Nyima Rinpoche
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:39:02.327836
  last_modified_at: 2022-02-28 22:39:02.327867
